//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashaCoursework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Sale_of_receipt = new HashSet<Sale_of_receipt>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Sale_date { get; set; }
        public Nullable<decimal> Sum { get; set; }
    
        public virtual Product Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_of_receipt> Sale_of_receipt { get; set; }
    }
}
